name: Deployment On K8s Cluster

on: 
  push: 
     branches: ['main']
  pull_request:
     branches: ['main']        

jobs:
  Docker_Image:
    name: Deploy Application On K8s Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo 
        uses: actions/checkout@v3
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}   

      # - name: Generate unique image  tag
      #   id: new_tag
      #   run: echo "::set-output name=tag::$(echo ${GITHUB_SHA::8})" 

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  #  Here the . represents the root directory of the repository where the workflow is running. We can change this value if your Dockerfile is located in a different directory.
          push: true
          tags: bhasmeht/angular-image:${{ github.run_number }}    # :${{ steps.new_tag.outputs.tag }}
  modifygit:
    needs: Docker_Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: 'bhaskarmehta/CICDUsingArgoCD'
          token: ${{ secrets.GIT_PASSWORD }}
      - name: modify the image
        run: |
          git config user.email bhaskarmehta422@gmail.com
          git config user.name Bhaskar
          pwd
          cat Deployments/deployment.yml
          pwd
          sed -i "s+bhasmeht/angular-image.*+bhasmeht/angular-image:$RUN_NUMBER+g" Deployments/
          # cat deployment.yml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}        